#!/bin/bash

# LICENSED UNDER GPLv3.0
# DON'T BLAME ME FOR BREAKING YOUR SYSTEM

which ffcast &> /dev/null
if [ $? != 0 ]; then
    echo "Dependency missing: ffcast"
    echo "Available in the AUR: cower -dd ffcast"
    return 1
fi

which xclip &> /dev/null
if [ $? != 0 ]; then
    echo "Dependency missing: xclip"
    echo "Available in Extra: pacman -S xclip"
    return 1
fi

TMP_AVI=$(mktemp /tmp/outXXXXXXXXXX.avi)
OUT="$(mktemp /tmp/outXXXXXXXXXX.gif)"
ffcast -s % ffmpeg -y -f x11grab -show_region 1 -framerate 15    \
	   -video_size %s -i %D+%c -codec:v huffyuv                  \
	   -vf crop="iw-mod(iw\\,2):ih-mod(ih\\,2)" $TMP_AVI         \
	   && convert -set delay 10 -layers Optimize $TMP_AVI $OUT;
res=$(curl -F c=@$OUT https://ptpb.pw | awk -F'url:' '{print $2}') && (printf $res | xclip -sel clip; printf "\a")
notify-send $res
